-- Etend PlayingCharacters pour Character::LoadCharacter (SELECT complet)
-- + valeurs par defaut pour TestPlayer (Light Haven, monde 0).
-- A lancer apres bootstrap_auth_mariadb.sql si la table n'a que 4 colonnes.

USE t4c_server;

ALTER TABLE PlayingCharacters
  ADD COLUMN IF NOT EXISTS wlX INT UNSIGNED NOT NULL DEFAULT 2880,
  ADD COLUMN IF NOT EXISTS wlY INT UNSIGNED NOT NULL DEFAULT 1083,
  ADD COLUMN IF NOT EXISTS wlWorld INT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS nClass INT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS CurrentHP INT UNSIGNED NOT NULL DEFAULT 100,
  ADD COLUMN IF NOT EXISTS MaxHP INT UNSIGNED NOT NULL DEFAULT 100,
  ADD COLUMN IF NOT EXISTS CurrentMana INT UNSIGNED NOT NULL DEFAULT 50,
  ADD COLUMN IF NOT EXISTS MaxMana INT UNSIGNED NOT NULL DEFAULT 50,
  ADD COLUMN IF NOT EXISTS Strength INT UNSIGNED NOT NULL DEFAULT 12,
  ADD COLUMN IF NOT EXISTS Endurance INT UNSIGNED NOT NULL DEFAULT 12,
  ADD COLUMN IF NOT EXISTS Agility INT UNSIGNED NOT NULL DEFAULT 12,
  ADD COLUMN IF NOT EXISTS Intelligence INT UNSIGNED NOT NULL DEFAULT 12,
  ADD COLUMN IF NOT EXISTS Wisdom INT UNSIGNED NOT NULL DEFAULT 12,
  ADD COLUMN IF NOT EXISTS AttackSkill INT UNSIGNED NOT NULL DEFAULT 10,
  ADD COLUMN IF NOT EXISTS DodgeSkill INT UNSIGNED NOT NULL DEFAULT 10,
  ADD COLUMN IF NOT EXISTS Gold INT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS Corpse INT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS XP DOUBLE NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS StatPnts INT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS SkillPnts INT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS Karma INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS Gender INT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ListingTitle VARCHAR(64) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS ListingMisc VARCHAR(64) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS MoveExhaust INT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS MentalExhaust INT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS AttackExhaust INT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS Luck INT UNSIGNED NOT NULL DEFAULT 10,
  ADD COLUMN IF NOT EXISTS GuildName VARCHAR(32) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS GuildID INT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS GuildChestAccess INT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS TotalDeathNumber INT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS TotalKillNumber INT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS CurrentDeathNumber INT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS CurrentKillNumber INT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS BestSerieMurder INT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS CurrentSerieMurder INT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS CurrentPvpPoint INT UNSIGNED NOT NULL DEFAULT 0;

UPDATE PlayingCharacters SET
  AccountName = 'test',
  Appearance = 0,
  CurrentLevel = 1,
  wlX = 2880, wlY = 1083, wlWorld = 0,
  CurrentHP = 100, MaxHP = 100,
  CurrentMana = 50, MaxMana = 50,
  Strength = 12, Endurance = 12, Agility = 12,
  Intelligence = 12, Wisdom = 12, Luck = 10,
  AttackSkill = 10, DodgeSkill = 10
WHERE PlayerName = 'TestPlayer';

-- Puis : mysql ... < tools/sql/seed_character_load_tables_mariadb.sql
