#ifndef T4C_LINUX_NPC_REGION_NPCS_RENAME_H
#define T4C_LINUX_NPC_REGION_NPCS_RENAME_H
// Generated by tools/gen_linux_npc_region_rename.py

#define GeenaNPC NPCs_GeenaNPC
#define KilhiamNPC NPCs_KilhiamNPC
#define MoonrockNPC NPCs_MoonrockNPC
#define FaliNPC NPCs_FaliNPC
#define Lord_Kirlor NPCs_Lord_Kirlor
#define MurmuntagDestroyNPC NPCs_MurmuntagDestroyNPC
#define Nobleman NPCs_Nobleman
#define DragonNPC NPCs_DragonNPC
#define DelvarIrongripNPC NPCs_DelvarIrongripNPC
#define AraknorNPC NPCs_AraknorNPC
#define Female_NPC NPCs_Female_NPC
#define ShadowNPC NPCs_ShadowNPC
#define Guard_One NPCs_Guard_One
#define Priest NPCs_Priest
#define Peasant NPCs_Peasant
#define Mage NPCs_Mage
#define _Pig NPCs__Pig
#define Balork NPCs_Balork
#define OrtanalasNPC NPCs_OrtanalasNPC
#define ShopKeeper NPCs_ShopKeeper
#define UranosNPC NPCs_UranosNPC
#define EdgarNPC NPCs_EdgarNPC
#define IsulgurNPC NPCs_IsulgurNPC
#define MarkamNPC NPCs_MarkamNPC
#define MarnecSunimNPC NPCs_MarnecSunimNPC
#define KalastorNPC NPCs_KalastorNPC
#define HalamNPC NPCs_HalamNPC
#define JalusNPC NPCs_JalusNPC

#endif
