#!/usr/bin/env python3
"""Emit per-region cpp macros for monolithic Linux NPC linkage (T4Serv3 paths)."""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "Exe Server" / "linux_npc_region"
OUT_DIR.mkdir(parents=True, exist_ok=True)

REGIONS = [
    ("Dll Gameops", "GameOps"),
    ("Dll Npcs", "NPCs"),
    ("Dll Npcs Addon", "NPCAddOn"),
    ("Dll Npcs Arakas", "Arakas"),
    ("Dll Npcs RavensDust", "RavensDust"),
    ("Dll Npcs Remort", "Remort"),
    ("Dll Npcs Stoneheim", "Stoneheim"),
    ("Dll Npcs WindHowl", "WindHowl"),
]

PAT = re.compile(r"^\s*NPCstructure::NPC\s+(\w+)\s*;")


def main() -> None:
    for folder, sym in REGIONS:
        mss = ROOT / folder / "MonsterStatSetup.cpp"
        text = mss.read_text(encoding="utf-8", errors="replace")
        names = [m.group(1) for line in text.splitlines() if (m := PAT.match(line))]
        guard = f"T4C_LINUX_NPC_REGION_{sym.upper()}_RENAME_H"
        lines = [
            f"#ifndef {guard}",
            f"#define {guard}",
            "// Generated by tools/gen_linux_npc_region_rename.py",
            "",
        ]
        lines += [f"#define {n} {sym}_{n}" for n in names]
        lines.extend(["", "#endif", ""])
        out = OUT_DIR / f"{sym}_rename.h"
        out.write_text("\n".join(lines), encoding="utf-8")
        print(f"Wrote {out.relative_to(ROOT)} ({len(names)} symbols)")


if __name__ == "__main__":
    main()
